# This is a basic workflow to help you get started with Actions

name: CI/CD Test

# Controls when the workflow will run
on:
  push:
    branches: [ "milestone5" ]
  pull_request:
    branches: [ "milestone5" ]
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:10.11
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: hiremenow
          MYSQL_USER: hmuser
          MYSQL_PASSWORD: hmpass
        ports: [3306]

      rabbitmq:
        image: rabbitmq:3-management-alpine
        ports: [5672, 15672]

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin

      - name: Build
        run: |
          mvn -B -f auth_service/pom.xml -DskipTests package
          mvn -B -f job_service/pom.xml -DskipTests package
          mvn -B -f application_service/pom.xml -DskipTests package

      - name: Start system
        run: docker-compose up -d

      - name: Wait
        run: sleep 70

      - name: Test apply
        run: curl -X POST http://localhost:8083/api/applications -H "Content-Type: application/json" -d '{"studentId":1,"jobId":1}'

      - name: Check async log
        run: |
          sleep 5
          docker logs hiremenow-job | grep "ASYNC EVENT RECEIVED" || (echo "FAILED" && exit 1)

      - name: DONE
        run: echo "GRADE 10 ACHIEVED"
